markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true

title_tag_text: Projet Compromis
h1_tag_text: Projet Compromis
